apiVersion: v1
kind: Service
metadata:
  name: digisign-fe-service
spec:
  selector:
    app: digisign-fe
  ports:
  - port: 6008
    protocol: "TCP"
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digisign-fe-deployment
spec:
  selector:
    matchLabels:
      app: digisign-fe
  replicas: 1
  template:
    metadata:
      labels:
        app: digisign-fe
    spec:
      containers:
      - name: nginx
        image: "batteryho/digisign-fe:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 80